import time
import serial

# XBee setting
serdev = '/dev/ttyUSB0'
s = serial.Serial(serdev, 9600)
s.write("+++".encode())
char = s.read(2)
print("Enter AT mode.")
print(char.decode())
s.write("ATMY 123\r\n".encode())
char = s.read(3)
print("Set MY 123.")
print(char.decode())
s.write("ATDL 456\r\n".encode())
char = s.read(3)
print("Set DL 456.")
print(char.decode())
s.write("ATID 0x1\r\n".encode())
char = s.read(3)
print("Set PAN ID 0x1.")
print(char.decode())
s.write("ATWR\r\n".encode())
char = s.read(3)
print("Write config.")
print(char.decode())
s.write("ATMY\r\n".encode())
char = s.read(4)
print("MY :")
print(char.decode())
s.write("ATDL\r\n".encode())
char = s.read(4)
print("DL : ")
print(char.decode())
s.write("ATCN\r\n".encode())
char = s.read(3)
print("Exit AT mode.")
print(char.decode())

print("start sending RPC")

while True:
    d1 = float(input('d1: '))
    d2 = float(input('d2: '))
    dir = float(input('direction(0~360): '))
    s.write(("/setpose/run %f %f %f \n"%(d1, d2, dir)).encode())
    # time.sleep(5)